version: "3.9"

services:
    roblox-ts-forge:
        container_name: roblox-ts-forge
        image: forge:latest
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workspace:cached
            - node_modules:/workspace/node_modules
        working_dir: /workspace
        environment:
            VENV_PATH: /opt/venv
            NODE_VERSION: 20.x
            ZSH_CUSTOM: /root/.oh-my-zsh/custom
            PATH: /root/.rokit/bin:/usr/local/bin:$PATH
        command: zsh
        stdin_open: true
        tty: true

volumes:
    node_modules:
